- hosts: localhost
  become: yes
  become_user: frankker
  vars:
    ansible_become_pass: chingiap83
    jenkins_hostname: localhost
    docker_users:
      - jenkins
  roles:
    - role: geerlingguy.jenkins
    - role: geerlingguy.docker